Repository AY2122S1-CS2103-F09-3/tp, pull requests merged in 2021-10, with the labels that each got.

#66 Ignore hidden folders and bin/
  .gitignore
Labels: priority.Medium

#65 Rename boolean variable and method to sound more like booleans
  src/main/java/seedu/address/logic/commands/PurgeCommand.java
Labels: priority.High

#69 v1.2_testcase_peiduo
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/ClassId.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/StudentId.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: priority.Medium, type.Bug

#68 Fixes for Parser Test Cases Version 1
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/ClassId.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Bug

#75 Add documentation for parameters
  README.md
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.Medium, type.docs

#351 Fix #343, #339
  docs/images/commands/HelpCommand/help.png
  src/main/java/seedu/programmer/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug

#324 Fix StudentId error message
  src/main/java/seedu/programmer/model/student/StudentId.java
  src/test/java/seedu/programmer/model/FileManagerTest.java
Labels: type.Bug

#359 Improve error messages for Edit
  docs/UserGuide.md
  src/main/java/seedu/programmer/logic/commands/EditLabCommand.java
  src/test/java/seedu/programmer/logic/commands/EditLabCommandTest.java
  src/test/java/seedu/programmer/testutil/TypicalLabs.java
Labels: type.Bug

#358 Fix minor UG errors
  docs/UserGuide.md
Labels: type.Bug, type.docs

#357 Fix #337, #321, #310
  src/main/java/seedu/programmer/logic/Logic.java
  src/main/java/seedu/programmer/logic/LogicManager.java
  src/main/java/seedu/programmer/logic/commands/AddCommand.java
  src/main/java/seedu/programmer/logic/commands/AddLabCommand.java
  src/main/java/seedu/programmer/logic/commands/DeleteCommand.java
  src/main/java/seedu/programmer/logic/commands/DeleteLabCommand.java
  src/main/java/seedu/programmer/logic/commands/EditCommand.java
  src/main/java/seedu/programmer/logic/commands/EditLabCommand.java
  src/main/java/seedu/programmer/logic/commands/PurgeCommand.java
  src/main/java/seedu/programmer/logic/commands/ShowCommand.java
  src/main/java/seedu/programmer/model/Model.java
  src/main/java/seedu/programmer/model/ModelManager.java
  src/main/java/seedu/programmer/model/ProgrammerError.java
  src/main/java/seedu/programmer/model/ReadOnlyProgrammerError.java
  src/main/java/seedu/programmer/model/student/DisplayableObject.java
  src/main/java/seedu/programmer/model/student/Lab.java
  src/main/java/seedu/programmer/model/student/Student.java
  src/main/java/seedu/programmer/model/student/UniqueStudentList.java
  src/main/java/seedu/programmer/ui/LabResultListPanel.java
  src/main/java/seedu/programmer/ui/MainWindow.java
  src/main/java/seedu/programmer/ui/StudentParticularPanel.java
  src/main/resources/view/LabResultListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/programmer/logic/commands/AddCommandTest.java
  src/test/java/seedu/programmer/model/ProgrammerErrorTest.java
Labels: type.Bug

#373 Fix tokenizer to ensure negative values are not parsed as flags
  src/main/java/seedu/programmer/logic/parser/ArgumentTokenizer.java
  src/test/java/seedu/programmer/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/programmer/logic/parser/EditLabCommandParserTest.java
Labels: type.Bug

#374 Fix Documentation issues: #303 #308 #315
  docs/UserGuide.md
Labels: type.Bug, type.docs

#371 Fix #329: Overflowing dashboard
  src/main/java/seedu/programmer/ui/DashboardWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DashboardWindow.fxml
Labels: type.Bug
